### ISSUE TITLE
Add Binaries For Linux

### ISSUE THREAD

**Issue by bauripalash** [arocks/punchscript#1]
Add Binary Support For Linux.

**Comment by arocks** [comment]
Not sure if you mean binaries or binary support. My development machine was on Ubuntu Linux, so it is definitely supported. Running `make release` produces byte code binaries which can be run on Linux using `make run`.

**Comment by bauripalash** [comment]
I got confused because of this in Makefile :
```
EXECUTABLE := punch.exe
```

So, Closing 👍
